# .goreleaser.yml
# Build customization
builds:
  - main: ./cmd/helm-kubelinter/main.go
    binary: helm-kubelinter
    ldflags: -s -w -X github.com/rm3l/helm-kubelinter/cmd/helm-kubelinter/cmd.version={{.Version}} -X github.com/rm3l/helm-kubelinter/cmd/helm-kubelinter/cmd.commit={{.Commit}} -X github.com/rm3l/helm-kubelinter/cmd/helm-kubelinter/cmd.date={{.Date}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - id: helm-kubelinter
    format: tar.gz
    replacements:
      amd64: x86_64
      darwin: Darwin
      linux: Linux
