name: "kubelinter"
version: "0.1.0"
usage: "helm kubelinter <my_chart> [any other Helm options]"
description: |-
  Validate Charts using KubeLinter
ignoreFlags: true
command: "$HELM_PLUGIN_DIR/bin/helm-kubelinter"
hooks:
  install: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
  update: "cd $HELM_PLUGIN_DIR; ./scripts/install.sh"
